# Generated by Django 5.2 on 2025-04-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comics/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
