# Generated by Django 5.2 on 2025-04-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0002_alter_autor_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('ES', 'España'), ('MX', 'México'), ('US', 'Estados Unidos'), ('DE', 'Alemania'), ('IN', 'India')], max_length=2),
        ),
    ]
